### ISSUE TITLE
Use of Var

### ISSUE THREAD

**Issue by mmatongo** [cazterk/learn_js#1]
https://github.com/cazterk/learn_js/blob/6692ff96cd14e7b747af063041283a207a3748ad/learn.js#L3

The `var` keyword is deprecated as of Js ES6 and is not good practice to use it.

**Comment by cazterk** [comment]
for now it's just to learning purposes,

**Comment by mmatongo** [comment]
You can use `let` or `const` in place of `var`

**Comment by cazterk** [comment]
> You can use `let` or `const` in place of `var`

I will correct that later for now this is when i'm trying to learn js in a serious way, though `let `  and `const` have their limitations too

**Comment by mmatongo** [comment]
`var` creates unnecessary overhead because of global scoping

**Comment by cazterk** [comment]
i heard something about global scoping and the like
